# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'girisekrani.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GirisEkran(object):
    def setupUi(self, GirisEkran):
        GirisEkran.setObjectName("GirisEkran")
        GirisEkran.resize(339, 201)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GirisEkran.sizePolicy().hasHeightForWidth())
        GirisEkran.setSizePolicy(sizePolicy)
        GirisEkran.setMaximumSize(QtCore.QSize(68139, 68139))
        GirisEkran.setMouseTracking(False)
        self.girisbuton = QtWidgets.QPushButton(GirisEkran)
        self.girisbuton.setGeometry(QtCore.QRect(200, 140, 75, 23))
        self.girisbuton.setObjectName("girisbuton")
        self.layoutWidget = QtWidgets.QWidget(GirisEkran)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 50, 121, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_2.raise_()
        self.label.raise_()
        self.layoutWidget1 = QtWidgets.QWidget(GirisEkran)
        self.layoutWidget1.setGeometry(QtCore.QRect(160, 50, 131, 71))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_kullaniciadi = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_kullaniciadi.setObjectName("lineEdit_kullaniciadi")
        self.verticalLayout_2.addWidget(self.lineEdit_kullaniciadi)
        self.lineEdit_sifre = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_sifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_sifre.setObjectName("lineEdit_sifre")
        self.verticalLayout_2.addWidget(self.lineEdit_sifre)

        self.retranslateUi(GirisEkran)
        QtCore.QMetaObject.connectSlotsByName(GirisEkran)

    def retranslateUi(self, GirisEkran):
        _translate = QtCore.QCoreApplication.translate
        GirisEkran.setWindowTitle(_translate("GirisEkran", "Form"))
        self.girisbuton.setText(_translate("GirisEkran", "GİRİŞ YAP"))
        self.label.setText(_translate("GirisEkran", "KULLANICI ADI:"))
        self.label_2.setText(_translate("GirisEkran", "ŞİFRE:"))
