# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kayitsil.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Kayitsil(object):
    def setupUi(self, Kayitsil):
        Kayitsil.setObjectName("Kayitsil")
        Kayitsil.resize(232, 165)
        self.pushButton_kayitsil_sil = QtWidgets.QPushButton(Kayitsil)
        self.pushButton_kayitsil_sil.setGeometry(QtCore.QRect(30, 110, 75, 23))
        self.pushButton_kayitsil_sil.setObjectName("pushButton_kayitsil_sil")
        self.layoutWidget = QtWidgets.QWidget(Kayitsil)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 50, 179, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_KayitSil = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_KayitSil.setObjectName("lineEdit_KayitSil")
        self.horizontalLayout.addWidget(self.lineEdit_KayitSil)

        self.retranslateUi(Kayitsil)
        QtCore.QMetaObject.connectSlotsByName(Kayitsil)

    def retranslateUi(self, Kayitsil):
        _translate = QtCore.QCoreApplication.translate
        Kayitsil.setWindowTitle(_translate("Kayitsil", "Form"))
        self.pushButton_kayitsil_sil.setText(_translate("Kayitsil", "Sil"))
        self.label.setText(_translate("Kayitsil", "Stok Id:"))
