# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stokhareket.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StokHareket(object):
    def setupUi(self, StokHareket):
        StokHareket.setObjectName("StokHareket")
        StokHareket.resize(668, 647)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        StokHareket.setFont(font)
        self.tableWidget_alt = QtWidgets.QTableWidget(StokHareket)
        self.tableWidget_alt.setGeometry(QtCore.QRect(70, 180, 541, 421))
        self.tableWidget_alt.setRowCount(30)
        self.tableWidget_alt.setObjectName("tableWidget_alt")
        self.tableWidget_alt.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_alt.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_alt.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_alt.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_alt.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_alt.setHorizontalHeaderItem(4, item)
        self.pushButton_HareketAra = QtWidgets.QPushButton(StokHareket)
        self.pushButton_HareketAra.setGeometry(QtCore.QRect(410, 60, 75, 23))
        self.pushButton_HareketAra.setObjectName("pushButton_HareketAra")
        self.tableWidget_ust = QtWidgets.QTableWidget(StokHareket)
        self.tableWidget_ust.setGeometry(QtCore.QRect(20, 100, 641, 61))
        self.tableWidget_ust.setRowCount(1)
        self.tableWidget_ust.setColumnCount(6)
        self.tableWidget_ust.setObjectName("tableWidget_ust")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ust.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ust.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ust.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ust.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ust.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ust.setHorizontalHeaderItem(5, item)
        self.pushButton_sil = QtWidgets.QPushButton(StokHareket)
        self.pushButton_sil.setGeometry(QtCore.QRect(270, 600, 101, 31))
        self.pushButton_sil.setObjectName("pushButton_sil")
        self.lineEdit_hareketara = QtWidgets.QLineEdit(StokHareket)
        self.lineEdit_hareketara.setGeometry(QtCore.QRect(190, 60, 201, 21))
        self.lineEdit_hareketara.setObjectName("lineEdit_hareketara")

        self.retranslateUi(StokHareket)
        QtCore.QMetaObject.connectSlotsByName(StokHareket)

    def retranslateUi(self, StokHareket):
        _translate = QtCore.QCoreApplication.translate
        StokHareket.setWindowTitle(_translate("StokHareket", "Form"))
        item = self.tableWidget_alt.horizontalHeaderItem(0)
        item.setText(_translate("StokHareket", "Fatura Numara"))
        item = self.tableWidget_alt.horizontalHeaderItem(1)
        item.setText(_translate("StokHareket", "Fatura Tarih"))
        item = self.tableWidget_alt.horizontalHeaderItem(2)
        item.setText(_translate("StokHareket", "Satıcı"))
        item = self.tableWidget_alt.horizontalHeaderItem(3)
        item.setText(_translate("StokHareket", "Alıcı"))
        item = self.tableWidget_alt.horizontalHeaderItem(4)
        item.setText(_translate("StokHareket", "Adet"))
        self.pushButton_HareketAra.setText(_translate("StokHareket", "ARA"))
        item = self.tableWidget_ust.horizontalHeaderItem(0)
        item.setText(_translate("StokHareket", "ID"))
        item = self.tableWidget_ust.horizontalHeaderItem(1)
        item.setText(_translate("StokHareket", "Stok Adı"))
        item = self.tableWidget_ust.horizontalHeaderItem(2)
        item.setText(_translate("StokHareket", "Marka"))
        item = self.tableWidget_ust.horizontalHeaderItem(3)
        item.setText(_translate("StokHareket", "Model"))
        item = self.tableWidget_ust.horizontalHeaderItem(4)
        item.setText(_translate("StokHareket", "Toplam Miktar"))
        item = self.tableWidget_ust.horizontalHeaderItem(5)
        item.setText(_translate("StokHareket", "Açıklama"))
        self.pushButton_sil.setText(_translate("StokHareket", "SİL"))
