# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stokcikis.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StokCikis(object):
    def setupUi(self, StokCikis):
        StokCikis.setObjectName("StokCikis")
        StokCikis.resize(400, 286)
        self.layoutWidget = QtWidgets.QWidget(StokCikis)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 40, 261, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit_StokCikis_ID = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_StokCikis_ID.setObjectName("lineEdit_StokCikis_ID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_StokCikis_ID)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_StokCikis_Adet = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_StokCikis_Adet.setObjectName("lineEdit_StokCikis_Adet")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_StokCikis_Adet)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_Stok_Cikis_Alici = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_Stok_Cikis_Alici.setObjectName("lineEdit_Stok_Cikis_Alici")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Stok_Cikis_Alici)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_StokCikis_FaturTarih = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_StokCikis_FaturTarih.setObjectName("lineEdit_StokCikis_FaturTarih")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_StokCikis_FaturTarih)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_StokCikis_FaturaNumara = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_StokCikis_FaturaNumara.setObjectName("lineEdit_StokCikis_FaturaNumara")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_StokCikis_FaturaNumara)
        self.pushButton_StokCikis_CikisYap = QtWidgets.QPushButton(StokCikis)
        self.pushButton_StokCikis_CikisYap.setGeometry(QtCore.QRect(60, 220, 75, 23))
        self.pushButton_StokCikis_CikisYap.setObjectName("pushButton_StokCikis_CikisYap")

        self.retranslateUi(StokCikis)
        QtCore.QMetaObject.connectSlotsByName(StokCikis)

    def retranslateUi(self, StokCikis):
        _translate = QtCore.QCoreApplication.translate
        StokCikis.setWindowTitle(_translate("StokCikis", "Form"))
        self.label.setText(_translate("StokCikis", "StokId:"))
        self.label_3.setText(_translate("StokCikis", "Çıkış Adet:"))
        self.label_4.setText(_translate("StokCikis", "Alıcı:"))
        self.label_2.setText(_translate("StokCikis", "Fatura Tarih:"))
        self.label_5.setText(_translate("StokCikis", "Fatura Numara:"))
        self.pushButton_StokCikis_CikisYap.setText(_translate("StokCikis", "Çıkış Yap"))
