# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stokgiris.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(350, 293)
        self.pushButton_GirisYap = QtWidgets.QPushButton(Form)
        self.pushButton_GirisYap.setGeometry(QtCore.QRect(50, 250, 75, 23))
        self.pushButton_GirisYap.setObjectName("pushButton_GirisYap")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 50, 261, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit_StokgirisID = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_StokgirisID.setObjectName("lineEdit_StokgirisID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_StokgirisID)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_Stokgiris_Adet = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_Stokgiris_Adet.setObjectName("lineEdit_Stokgiris_Adet")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Stokgiris_Adet)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_StokGiris_Tedarikci = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_StokGiris_Tedarikci.setObjectName("lineEdit_StokGiris_Tedarikci")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_StokGiris_Tedarikci)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_StokGiris_FaturaTarih = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_StokGiris_FaturaTarih.setObjectName("lineEdit_StokGiris_FaturaTarih")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_StokGiris_FaturaTarih)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_StokGiris_FaturaNumara = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_StokGiris_FaturaNumara.setObjectName("lineEdit_StokGiris_FaturaNumara")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_StokGiris_FaturaNumara)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_GirisYap.setText(_translate("Form", "Giriş Yap"))
        self.label.setText(_translate("Form", "StokId:"))
        self.label_3.setText(_translate("Form", "Giriş Adet:"))
        self.label_4.setText(_translate("Form", "Tedarikçi:"))
        self.label_2.setText(_translate("Form", "Fatura Tarih:"))
        self.label_5.setText(_translate("Form", "Fatura Numara:"))
